[package]
name = "jenkins-sdk"
description = "Jenkins API SDK in pure Rust with async and blocking clients, typed endpoints, pluggable middleware, and zero magic strings."
version = "0.1.14"
edition = "2024"
license = "MIT"
authors = ["lvillis<lvillis@outlook.com>"]
repository = "https://github.com/lvillis/jenkins-sdk-rust"
homepage = "https://github.com/lvillis/jenkins-sdk-rust"
documentation = "https://github.com/lvillis/jenkins-sdk-rust#readme"
exclude = [
    "/docs/",
    "/tests/",
    "/.config/",
    "/.github/",
    "/.justfile",
    "/rust-toolchain.toml",
    "/.gitignore",
    "/.aiignore"
]

[features]
default = ["async-client"]
async-client = ["reqwest", "tokio", "async-trait"]
blocking-client = ["reqwest/blocking"]

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
http = "1.4.0"
base64 = "0.22.1"
url = "2.5.7"

# async-only deps
async-trait = { version = "0.1.89", optional = true }
tokio = { version = "1.48.0", optional = true, features = ["macros", "rt-multi-thread"] }

# HTTP stack
reqwest = { version = "0.12.25", default-features = false, features = ["json", "rustls-tls", "cookies"], optional = true }

[dev-dependencies]
anyhow = { version = "1.0.100" }
wiremock = { version = "0.6.5" }

[[example]]
name = "async_test"
path = "examples/async_test.rs"
required-features = ["async-client"]

[[example]]
name = "sync_test"
path = "examples/sync_test.rs"
required-features = ["blocking-client"]

[package.metadata.release]
tag-prefix = ""
tag-name = "{{prefix}}{{version}}"
pre-release-commit-message = "chore: release {{crate_name}} version {{version}}"
tag-message = "chore: release {{crate_name}} version {{version}}"
pre-release-hook = ["git", "cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}"]
