[package]
name = "jenkins-sdk"
description = "ðŸ“¦ Jenkins API SDK written in Rust"
version = "0.1.6"
edition = "2024"
license = "MIT"
authors = ["lvillis<lvillis@outlook.com>"]
repository = "https://github.com/lvillis/jenkins-sdk-rust"
homepage = "https://github.com/lvillis/jenkins-sdk-rust"
documentation = "https://github.com/lvillis/jenkins-sdk-rust/blob/main/README.md"
exclude = [
    "/docs/",
    "/tests/",
    "/.config/",
    "/.github/",
    "/.justfile",
    "/rust-toolchain.toml",
    "/.gitignore",
]


[features]
default = ["async-client"]
async-client = ["reqwest", "tokio", "async-trait"]
blocking-client = ["reqwest/blocking"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2.0.12"
http = "1"
base64 = "0.22"
url = "2"

# async-only deps
async-trait = { version = "0.1", optional = true }
tokio = { version = "1", optional = true, features = ["macros", "rt-multi-thread"] }

# HTTP stack
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "cookies"], optional = true }

[dev-dependencies]
anyhow = { version = "1.0.98" }

[[example]]
name = "async_test"
path = "examples/async_test.rs"
required-features = ["async-client"]

[[example]]
name = "sync_test"
path = "examples/sync_test.rs"
required-features = ["blocking-client"]

[package.metadata.release]
tag-prefix = ""
tag-name = "{{prefix}}{{version}}"
pre-release-commit-message = "chore: release {{crate_name}} version {{version}}"
tag-message = "chore: release {{crate_name}} version {{version}}"
pre-release-hook = ["git", "cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}"]
